name: Check Lab02

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install spectral
        run: npm i -g @stoplight/spectral-cli
      - name: Run spectral lint
        run: spectral lint openapi.yaml -r campus-spectral.yaml
